### ISSUE TITLE
Old references of the SDK in the Wiki

### ISSUE THREAD

**Issue by davidalves2000** [Avixy/sdk_workspace#20]
In the wiki still have some references from the old version of the SDK.
(/home/sdk3400/workspace/sharedNFS *(rw,async,no_subtree_check,all_squash,anonuid=1000,anongid=1000))

**Comment by edhana** [comment]
@davidalves2000 I've changed the line you referenced to something like this (/home/<username>/workspace/sharedNFS ...

This should be enough
